### ISSUE TITLE
ошибка в описании установки

### ISSUE THREAD

**Issue by dvtaras2** [yandex-load/yatank-online#10]
В версии танка и репорт плагина:
   yandextank (1.7.29)
   yatank-online (0.0.9)
Указание тега :
[tank]
plugin_web=yandextank.plugins.Report

приводит к ошибке. Танк не запускается.

Рабочий вариант:
[tank]
plugin_web=yatank_OnlineReport
Поправьте пожалуйста в README

**Comment by Sobolev-Ilya** [comment]
> Рабочий вариант:
> [tank]
> plugin_web=yatank_OnlineReport
> Поправьте пожалуйста в README

Проблема действительно есть, я то думал, почему у меня не работало)

**Comment by direvius** [comment]
Прошу прощения, обновляю плагин под новый танк, раньше времени поправил доку. Добавил ссылку на старую доку и код в Readme: https://github.com/yandex-load/yatank-online/blob/master/README.md#attention-please

**Comment by dvtaras2** [comment]
Спасибо! 
Пробовал запустить и с последней версией, но не нашел в репе либу Queue. На этом попытки закончились)
